
[workspace]
resolver = "2"
members = [
    "gotcha",
    "gotcha_macro",
    "examples/*"
]
exclude = ["examples/clouldflare-worker"]
default-members = ["gotcha", "gotcha_macro"]

[workspace.dependencies]
cfg-if = "1"