[package]
name = "custom_types_simple"
version = "0.1.0"
edition = "2021"

[dependencies]
gotcha = { path = "../../gotcha" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing-subscriber = "0.3"